### ISSUE TITLE
Initial Auction Version

### ISSUE THREAD

**Issue by mikedunbar20** [mikedunbar20/auction-site#1]
Create an auction app that does the following: 

- Countdown timer that goes to zero when no additional bids have been set. 
- Countdown timer that resets to maximum time after a new bid has been entered
- After a user has won the bid, save the user and highest bid amount to the user
- Cycle to the next team that the users will bid on for the app
- Continue until all teams have been auctioned. At the end, say 'Auction is finished!'

**Comment by jhodapp** [comment]
Implemented successfully, closing.
